name: Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  vet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: vet
        run: go vet ./...
